### ISSUE TITLE
fuck you and your crawler

### ISSUE THREAD

**Issue by funnycatgaming** [tb0hdan/domains#19]
this shit is causing major issues for me and my project

**Comment by qu0laz** [comment]
How does it cause problems?

**Comment by funnycatgaming** [comment]
its enabling malicious actors to do malicious things towards my project and i dont appreciate it

**Comment by shev-pro** [comment]
> its enabling malicious actors to do malicious things towards my project and i dont appreciate it

security by obscurity is not a security, so domain discovery is not an issue at all.

**Comment by qu0laz** [comment]
@funnycatgaming All it does is visit web addresses and links. The same way Google has been crawling the web for 20+ years.

So how does it enable malicious actors? Please provide more details.

**Comment by funnycatgaming** [comment]
after it got my domain, random german ovh, digitalocean and linode servers starting trying to abuse my server with random user agents

**Comment by qu0laz** [comment]
@funnycatgaming Domain names are public, that is the whole point of a domain name. Those "malicious actors" could have found your domain through this repo (doubt it) or any other resource. You can buy a list of new domain names every month for less than $49.

IP addresses are also available to anyone, this is how IP addresses work.

If you don't want people visiting your site while it's in development you main page at a link no one will find, e.g. example.com/areallylonglinkname. If you don't want anyone to see anything because it's a secret than put it behind a login page.

Your complaining that people/bots are visiting your site but that's the whole point of the internet. You should not blame this repos author or google or icann and instead need to improve how your work on sites in development. It will solve your "malicious actor" issue and make you a better developer.

**Comment by tb0hdan** [comment]
I would like to thank my vibrant community for giving expanded responses. Indeed, crawler is completely open source and doesn't mean any harm. I consider this matter resolved.
